# typed: false
# frozen_string_literal: true

# This file was generated by unifictl. DO NOT EDIT.
class Unifictl < Formula
  desc "CLI for UniFi Site Manager (API v1/EA)"
  homepage "https://github.com/nachtschatt3n/unifictl"
  version "0.4.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.4.4/unifictl-x86_64-apple-darwin.tar.gz"
      sha256 "" # Will be updated automatically
    end
    if Hardware::CPU.arm?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.4.4/unifictl-aarch64-apple-darwin.tar.gz"
      sha256 "" # Will be updated automatically
    end
  end

  def install
    bin.install "unifictl"
  end

  test do
    system "#{bin}/unifictl", "--version"
  end
end
