# typed: false
# frozen_string_literal: true

# This file was generated by unifictl. DO NOT EDIT.
class Unifictl < Formula
  desc "🤖 AI-powered CLI for UniFi networks - LLM-optimized output, smart correlation & diagnostics"
  homepage "https://github.com/nachtschatt3n/unifictl"
  version "0.5.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.5.1/unifictl-x86_64-apple-darwin.tar.gz"
      sha256 "c21c7d85a0bba1d7a6858b20b192bafc4f702cb1b9d5f358f05f0bbce54cd2d9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.5.1/unifictl-aarch64-apple-darwin.tar.gz"
      sha256 "a9cdce5661d021f69af3091459d0de5f346c0b91cb0b2edb164f3d254aa5bf29"
    end
  end

  def install
    bin.install "unifictl"
  end

  test do
    system "#{bin}/unifictl", "--version"
  end
end
