# typed: false
# frozen_string_literal: true

# This file was generated by unifictl. DO NOT EDIT.
class Unifictl < Formula
  desc "🤖 AI-powered CLI for UniFi networks - LLM-optimized output, smart correlation & diagnostics"
  homepage "https://github.com/nachtschatt3n/unifictl"
  version "0.5.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.4.5/unifictl-x86_64-apple-darwin.tar.gz"
      sha256 "08eb33076cdb95b21b9fa810a7ee7ac0d310e7bbe63923a3ac5e803972479386"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nachtschatt3n/unifictl/releases/download/v0.4.5/unifictl-aarch64-apple-darwin.tar.gz"
      sha256 "9dbab71b9bc110a046057e575e77eaa2fd66cf874a5c5ade2c1d105752e48622"
    end
  end

  def install
    bin.install "unifictl"
  end

  test do
    system "#{bin}/unifictl", "--version"
  end
end
